remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have on

title: [sixmegabytes' useful stuff]
description: [I made this site so i can post things that can be useful this site can be updated anytime.]
